from __future__ import annotations

import winreg
from typing import Any

from tweaks.supplemental_catalog import SupplementalTweak

_CDM = r"HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"
_EXPL = r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer"
_EXPL_ADV = r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
_EXPL_POL = r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer"
_GAME = r"HKCU\System\GameConfigStore"
_MMCSS = r"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks"
_MM = r"HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management"
_DG = r"HKLM\SYSTEM\CurrentControlSet\Control\DeviceGuard"
_WU = r"HKLM\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings"
_WU_POL = r"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate"


def _b(
    tid: str,
    name: str,
    desc: str,
    cat: str,
    hint: str,
    entries: tuple = (),
    risk: str = "medium",
    reboot: bool = False,
    admin: bool = True,
    en_name: str = "",
    en_desc: str = "",
    en_hint: str = "",
    source: str = "Backlog",
) -> SupplementalTweak:
    return SupplementalTweak(
        id=tid,
        name=name,
        description=desc,
        category=cat,
        risk=risk,
        requires_admin=admin,
        requires_reboot=reboot,
        hint=hint,
        source=source,
        entries=list(entries),
        en_name=en_name,
        en_description=en_desc,
        en_hint=en_hint,
    )


def backlog_meta_items() -> list[dict[str, Any]]:
    from tweaks.supplemental_catalog import catalog_meta_items

    return catalog_meta_items(BACKLOG_TWEAKS)


def backlog_en_strings() -> dict[str, dict[str, str]]:
    from tweaks.supplemental_catalog import catalog_en_strings

    return catalog_en_strings(BACKLOG_TWEAKS)


PAUSE_UPDATES_EXTREME_ENTRIES = (
    (_WU, "FlightSettingsMaxPauseDays", 36500, 35),
    (_WU, "PauseFeatureUpdatesStartTime", 1, 0),
    (_WU, "PauseQualityUpdatesStartTime", 1, 0),
    (_WU_POL, "SetDisableUXWUAccess", 1, 0),
    (r"HKLM\SOFTWARE\Microsoft\WindowsUpdate\UpdatePolicy\Settings", "PausedFeatureStatus", 1, 0),
)

BACKLOG_SERVICE_MAP: dict[str, str] = {
    "disable_ndu_service": "Ndu",
    "disable_pca_service": "PcaSvc",
    "disable_pla_service": "pla",
    "disable_wap_push": "dmwappushservice",
    "disable_geolocation_service": "lfsvc",
    "disable_fax_service": "Fax",
    "disable_branchcache": "PeerDistSvc",
    "disable_wallet_service": "WalletService",
    "disable_mobile_hotspot": "icssvc",
    "disable_print_spooler": "Spooler",
    "disable_tablet_input_service": "TabletInputService",
    "disable_dcp_service": "DcpSvc",
    "disable_remote_registry": "RemoteRegistry",
    "disable_alljoyn_router": "AJRouter",
    "disable_media_player_sharing": "WMPNetworkSvc",
    "disable_smart_card": "SCardSvr",
    "disable_pim_index": "PimIndexMaintenanceSvc",
    "disable_retail_demo": "RetailDemo",
    "disable_parental_controls": "WpcMonSvc",
    "disable_biometrics": "WbioSrvc",
    "disable_gpu_energy_driver": "GpuEnergyDrv",
}

BACKLOG_TWEAKS: list[SupplementalTweak] = [
    # ── Gaming / Performance ──────────────────────────────────────────────
    _b(
        "disable_active_probing",
        "Отключить Active Probing (NLA)",
        "EnableActiveProbing=0 — меньше фоновых сетевых проверок",
        "network",
        "Снижает фоновый трафик · при проблемах с «нет интернета» — откат",
        entries=(
            (
                r"HKLM\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet",
                "EnableActiveProbing",
                0,
                1,
            ),
        ),
        en_name="Disable Active Probing (NLA)",
        en_desc="EnableActiveProbing=0 — fewer background network probes",
        en_hint="Less background traffic · revert if false 'no internet' icon",
    ),
    _b(
        "disable_fth",
        "Отключить Fault Tolerant Heap",
        "FTH Enabled=0 — меньше накладных расходов в старых 32-bit приложениях",
        "performance",
        "Может помочь FPS в legacy-играх · редкие краши старых программ",
        reboot=True,
        entries=((r"HKLM\SOFTWARE\Microsoft\FTH", "Enabled", 0, 1),),
        en_name="Disable Fault Tolerant Heap",
        en_desc="FTH Enabled=0 — lower overhead for legacy 32-bit apps",
        en_hint="May help FPS in legacy games · rare crashes in old apps",
    ),
    _b(
        "disable_core_isolation",
        "Отключить изоляцию ядра (Memory Integrity)",
        "HypervisorEnforcedCodeIntegrity и LsaCfgFlags — снижает накладные расходы VBS",
        "expert",
        "Эксперт · снижает защиту от kernel-exploit · перезагрузка обязательна",
        risk="high",
        reboot=True,
        entries=(
            (_DG + r"\Scenarios\HypervisorEnforcedCodeIntegrity", "Enabled", 0, 1),
            (r"HKLM\SYSTEM\CurrentControlSet\Control\Lsa", "LsaCfgFlags", 0, 1),
        ),
        en_name="Disable Core Isolation (Memory Integrity)",
        en_desc="Disables HypervisorEnforcedCodeIntegrity and LsaCfgFlags",
        en_hint="Expert · weaker kernel exploit protection · reboot required",
    ),
    _b(
        "disable_vbs",
        "Отключить VBS",
        "EnableVirtualizationBasedSecurity=0 — виртуализация безопасности OFF",
        "expert",
        "Эксперт · прирост производительности · слабее защита системы",
        risk="high",
        reboot=True,
        entries=((_DG, "EnableVirtualizationBasedSecurity", 0, 1),),
        en_name="Disable VBS",
        en_desc="EnableVirtualizationBasedSecurity=0",
        en_hint="Expert · performance gain · weaker system protection",
    ),
    _b(
        "enable_windowed_games_opt",
        "Оптимизация оконных игр (SwapEffect)",
        "SwapEffectUpgradeEnable=1 — улучшение flip model для оконного режима",
        "gaming",
        "Полезно для borderless/windowed · без перезагрузки",
        reboot=False,
        admin=False,
        entries=((_GAME, "SwapEffectUpgradeEnable", 1, 0),),
        en_name="Windowed Games Optimization (SwapEffect)",
        en_desc="SwapEffectUpgradeEnable=1 for windowed/borderless games",
        en_hint="Useful for borderless/windowed · no reboot",
    ),
    _b(
        "disable_energy_estimation",
        "Отключить оценку энергопотребления",
        "EnergyEstimation Enabled=0 — меньше фоновых power-метрик",
        "performance",
        "Небольшой выигрыш CPU · безопасно на desktop",
        entries=(
            (r"HKLM\SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation", "Enabled", 0, 1),
        ),
        en_name="Disable Energy Estimation",
        en_desc="EnergyEstimation Enabled=0 — fewer power metrics",
        en_hint="Small CPU savings · safe on desktops",
    ),
    _b(
        "mmcss_games_sfio_rate",
        "MMCSS Games: SFIO High",
        "SFIO Priority=High, GPU Priority=8, Priority=6 для профиля Games",
        "gaming",
        "Приоритет игрового потока · перезагрузка рекомендуется",
        reboot=True,
        entries=(
            (_MMCSS + r"\Games", "SFIO Priority", "High", "Normal", winreg.REG_SZ),
            (_MMCSS + r"\Games", "GPU Priority", 8, 2),
            (_MMCSS + r"\Games", "Priority", 6, 2),
        ),
        en_name="MMCSS Games: SFIO High",
        en_desc="SFIO Priority=High, GPU Priority=8, Priority=6 for Games profile",
        en_hint="Higher game thread priority · reboot recommended",
    ),
    _b(
        "mmcss_low_latency_profile",
        "MMCSS: профиль Low Latency",
        "Scheduling Category High, SFIO High, Priority 8 — профиль Low Latency",
        "gaming",
        "Низкая задержка аудио/игр · перезагрузка рекомендуется",
        reboot=True,
        entries=(
            (_MMCSS + r"\Low Latency", "Scheduling Category", "High", "Medium", winreg.REG_SZ),
            (_MMCSS + r"\Low Latency", "SFIO Priority", "High", "Normal", winreg.REG_SZ),
            (_MMCSS + r"\Low Latency", "Priority", 8, 2),
            (_MMCSS + r"\Low Latency", "GPU Priority", 8, 2),
        ),
        en_name="MMCSS: Low Latency Profile",
        en_desc="High scheduling/SFIO priority for Low Latency MMCSS task",
        en_hint="Lower audio/game latency · reboot recommended",
    ),
    _b(
        "disable_media_frame_server",
        "Отключить Media Frame Server",
        "EnableFrameServerMode=0 — меньше фоновой обработки камеры/медиа",
        "performance",
        "Полезно если камера не нужна · без перезагрузки",
        entries=(
            (
                r"HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows Media Foundation",
                "EnableFrameServerMode",
                0,
                1,
            ),
        ),
        en_name="Disable Media Frame Server",
        en_desc="EnableFrameServerMode=0",
        en_hint="Useful if camera unused · no reboot",
    ),
    _b(
        "disable_modern_standby",
        "Отключить Modern Standby (AoAc)",
        "PlatformAoAcOverride=0 — классический S3 sleep вместо Connected Standby",
        "performance",
        "Только если ПК не ноутбук с AoAc · может изменить поведение сна",
        reboot=True,
        entries=(
            (r"HKLM\SYSTEM\CurrentControlSet\Control\Power", "PlatformAoAcOverride", 0, 1),
        ),
        en_name="Disable Modern Standby (AoAc)",
        en_desc="PlatformAoAcOverride=0 — classic S3 instead of Connected Standby",
        en_hint="Skip on AoAc laptops · changes sleep behavior",
    ),
    _b(
        "disable_gpu_energy_driver",
        "Отключить службу GpuEnergyDrv",
        "Служба GpuEnergyDrv — Start=4 (отключена)",
        "performance",
        "Меньше GPU power telemetry · служба через backlog.py",
        reboot=True,
        entries=(),
        en_name="Disable GpuEnergyDrv Service",
        en_desc="Disables GpuEnergyDrv service (Start=4)",
        en_hint="Less GPU power telemetry · service handler in backlog.py",
    ),
    _b(
        "amd_disable_var_store",
        "AMD: отключить VAR Store (preemption)",
        "KMD_EnableComputePreemption=0 на GPU-адаптере AMD",
        "gaming",
        "Только AMD · может снизить stutter · перезагрузка",
        reboot=True,
        entries=(
            (
                r"HKLM\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000",
                "KMD_EnableComputePreemption",
                0,
                1,
            ),
        ),
        en_name="AMD: Disable VAR Store (Preemption)",
        en_desc="KMD_EnableComputePreemption=0 on AMD GPU adapter",
        en_hint="AMD only · may reduce stutter · reboot",
    ),
    _b(
        "optimize_pagefile_system_managed",
        "Pagefile: управление системой",
        "PagingFiles сброс — Windows сама управляет файлом подкачки",
        "performance",
        "Безопаснее фиксированного pagefile · перезагрузка",
        reboot=True,
        entries=(
            (_MM, "PagingFiles", "", None, winreg.REG_MULTI_SZ),
        ),
        en_name="Pagefile: System Managed",
        en_desc="Reset PagingFiles — let Windows manage pagefile",
        en_hint="Safer than fixed pagefile · reboot",
    ),
    _b(
        "disable_reserved_storage",
        "Отключить Reserved Storage",
        "ShippedWithReserves=0 — освобождает ~7 GB резерва Windows",
        "system",
        "Освобождает место на диске · обновления могут занять больше времени",
        entries=(
            (
                r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\ReserveManager",
                "ShippedWithReserves",
                0,
                1,
            ),
        ),
        en_name="Disable Reserved Storage",
        en_desc="ShippedWithReserves=0 — frees ~7 GB reserved space",
        en_hint="Frees disk space · updates may need more room",
    ),
    # ── Network ───────────────────────────────────────────────────────────
    _b(
        "disable_nic_rss",
        "Отключить NIC RSS",
        "Receive Side Scaling OFF на сетевых адаптерах (PowerShell)",
        "network",
        "Эксперимент для latency · handler в backlog.py · откат при сбоях",
        risk="high",
        reboot=True,
        entries=(),
        en_name="Disable NIC RSS",
        en_desc="Disable Receive Side Scaling on network adapters",
        en_hint="Latency experiment · PS handler · revert if unstable",
    ),
    # ── Privacy ───────────────────────────────────────────────────────────
    _b(
        "disable_windows_recall",
        "Отключить Windows Recall",
        "DisableAIDataAnalysis и AllowRecallEnablement=0 (+ DISM в handler)",
        "privacy",
        "Win11 24H2+ · handler добавит DISM · без Recall",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI", "DisableAIDataAnalysis", 1, 0),
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI", "AllowRecallEnablement", 0, 1),
        ),
        en_name="Disable Windows Recall",
        en_desc="DisableAIDataAnalysis and AllowRecallEnablement=0 (+ DISM in handler)",
        en_hint="Win11 24H2+ · handler runs DISM",
    ),
    _b(
        "disable_spotlight",
        "Отключить Windows Spotlight",
        "DisableWindowsSpotlightFeatures и связанные ключи ContentDeliveryManager",
        "privacy",
        "Без рекламы на экране блокировки · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_CDM, "DisableWindowsSpotlightFeatures", 1, 0),
            (_CDM, "RotatingLockWallpaperEnabled", 0, 1),
            (_CDM, "SubscribedContent-338387Enabled", 0, 1),
        ),
        en_name="Disable Windows Spotlight",
        en_desc="DisableWindowsSpotlightFeatures and related CDM keys",
        en_hint="No lock screen ads · safe",
    ),
    _b(
        "disable_lockscreen_tips",
        "Отключить советы на экране блокировки",
        "SubscribedContent-338387/338389 Enabled=0",
        "privacy",
        "Чистый lock screen · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_CDM, "SubscribedContent-338387Enabled", 0, 1),
            (_CDM, "SubscribedContent-338389Enabled", 0, 1),
            (_CDM, "SoftLandingEnabled", 0, 1),
        ),
        en_name="Disable Lock Screen Tips",
        en_desc="SubscribedContent-338387/338389 Enabled=0",
        en_hint="Clean lock screen · safe",
    ),
    _b(
        "disable_clipboard_sync",
        "Отключить синхронизацию буфера обмена",
        "AllowCrossDeviceClipboard=0, EnableClipboardHistory=0",
        "privacy",
        "Буфер только локально · без Phone Link sync",
        risk="safe",
        admin=False,
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\System", "AllowCrossDeviceClipboard", 0, 1),
            (r"HKCU\Software\Microsoft\Clipboard", "EnableClipboardHistory", 0, 1),
        ),
        en_name="Disable Clipboard Sync",
        en_desc="AllowCrossDeviceClipboard=0, EnableClipboardHistory=0",
        en_hint="Local clipboard only · no cross-device sync",
    ),
    _b(
        "disable_find_my_device",
        "Отключить «Найти мое устройство»",
        "AllowFindMyDevice=0",
        "privacy",
        "Меньше геолокации в облаке · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\FindMyDevice", "AllowFindMyDevice", 0, 1),
        ),
        en_name="Disable Find My Device",
        en_desc="AllowFindMyDevice=0",
        en_hint="Less cloud location tracking · safe",
    ),
    _b(
        "disable_settings_sync",
        "Отключить синхронизацию параметров",
        "DisableSettingSync=2 и группы SettingSync",
        "privacy",
        "Настройки не уходят в Microsoft account · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync", "DisableSettingSync", 2, 0),
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Accessibility", "Enabled", 0, 1),
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\BrowserSettings", "Enabled", 0, 1),
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Credentials", "Enabled", 0, 1),
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\DesktopTheme", "Enabled", 0, 1),
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Language", "Enabled", 0, 1),
        ),
        en_name="Disable Settings Sync",
        en_desc="DisableSettingSync=2 and SettingSync group keys",
        en_hint="Settings stay local · safe",
    ),
    _b(
        "disable_userassist_tracking",
        "Отключить UserAssist / MFU",
        "NoInstrumentation, Start_TrackDocs/Progs=0",
        "privacy",
        "Меньше статистики запуска программ · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_POL, "NoInstrumentation", 1, 0),
            (_EXPL_ADV, "Start_TrackDocs", 0, 1),
            (_EXPL_ADV, "Start_TrackProgs", 0, 1),
        ),
        en_name="Disable UserAssist / MFU Tracking",
        en_desc="NoInstrumentation, Start_TrackDocs/Progs=0",
        en_hint="Less program launch statistics · safe",
    ),
    _b(
        "disable_click_to_do",
        "Отключить Click to Do (AI overlay)",
        "DisableAIDataAnalysis и DisableClickToDo policies",
        "privacy",
        "Win11 AI overlay OFF · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI", "DisableAIDataAnalysis", 1, 0),
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI", "DisableClickToDo", 1, 0),
        ),
        en_name="Disable Click to Do (AI Overlay)",
        en_desc="DisableAIDataAnalysis and DisableClickToDo policies",
        en_hint="Win11 AI overlay OFF · safe",
    ),
    _b(
        "disable_suggested_settings",
        "Отключить предложения в Параметрах",
        "IsEnabledByDefault=0 для SettingsSuggestedContent",
        "privacy",
        "Меньше рекламы в Settings · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (
                r"HKCU\Software\Microsoft\Windows\CurrentVersion\Settings\SettingsSuggestedContent",
                "IsEnabledByDefault",
                0,
                1,
            ),
        ),
        en_name="Disable Suggested Settings",
        en_desc="IsEnabledByDefault=0 for SettingsSuggestedContent",
        en_hint="Less ads in Settings · safe",
    ),
    _b(
        "disable_third_party_suggestions",
        "Отключить сторонние предложения",
        "SubscribedContent-353694/353696 Enabled=0",
        "privacy",
        "Без сторонних подсказок в меню Пуск · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_CDM, "SubscribedContent-353694Enabled", 0, 1),
            (_CDM, "SubscribedContent-353696Enabled", 0, 1),
            (_CDM, "SubscribedContent-338388Enabled", 0, 1),
        ),
        en_name="Disable Third-Party Suggestions",
        en_desc="SubscribedContent-353694/353696 Enabled=0",
        en_hint="No third-party Start suggestions · safe",
    ),
    _b(
        "disable_office_connected",
        "Office: отключить Connected Experiences",
        "DisableTelemetry и sendcustomerdata policies",
        "privacy",
        "Меньше телеметрии Office · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Software\Microsoft\Office\Common\ClientTelemetry", "DisableTelemetry", 1, 0),
            (r"HKCU\Software\Policies\Microsoft\office\16.0\common", "sendcustomerdata", 0, 1),
            (r"HKCU\Software\Policies\Microsoft\office\16.0\common\feedback", "enabled", 0, 1),
        ),
        en_name="Office: Disable Connected Experiences",
        en_desc="DisableTelemetry and sendcustomerdata policies",
        en_hint="Less Office telemetry · safe",
    ),
    _b(
        "disable_chrome_telemetry",
        "Chrome: отключить телеметрию",
        "MetricsReportingEnabled=0 policy",
        "privacy",
        "Только если Chrome установлен · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Google\Chrome", "MetricsReportingEnabled", 0, 1),
        ),
        en_name="Chrome: Disable Telemetry",
        en_desc="MetricsReportingEnabled=0 policy",
        en_hint="If Chrome installed · safe",
    ),
    _b(
        "disable_firefox_telemetry",
        "Firefox: отключить телеметрию",
        "DisableTelemetry=1 policy",
        "privacy",
        "Только если Firefox установлен · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Mozilla\Firefox", "DisableTelemetry", 1, 0),
        ),
        en_name="Firefox: Disable Telemetry",
        en_desc="DisableTelemetry=1 policy",
        en_hint="If Firefox installed · safe",
    ),
    _b(
        "disable_visual_studio_telemetry",
        "Visual Studio: отключить Feedback",
        "Feedback Disabled=1 policy",
        "privacy",
        "Только если VS установлен · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\VisualStudio\Feedback", "Disabled", 1, 0),
        ),
        en_name="Visual Studio: Disable Feedback Telemetry",
        en_desc="Feedback Disabled=1 policy",
        en_hint="If VS installed · safe",
    ),
    _b(
        "disable_intel_telemetry",
        "Intel: отключить телеметрию",
        "IntelTelemetryAgentStart и связанные службы — Start=4",
        "privacy",
        "Меньше Intel background · перезагрузка",
        reboot=True,
        entries=(
            (r"HKLM\SYSTEM\CurrentControlSet\Services\IntelTelemetryAgent", "Start", 4, 3),
            (r"HKLM\SYSTEM\CurrentControlSet\Services\Telemetry", "Start", 4, 3),
        ),
        en_name="Intel: Disable Telemetry Services",
        en_desc="IntelTelemetryAgent and Telemetry services Start=4",
        en_hint="Less Intel background · reboot",
    ),
    _b(
        "disable_appcompat_engine",
        "Отключить AppCompat Engine",
        "DisableEngine=1, DisablePCA=1",
        "privacy",
        "Меньше совместимости shim · редкие проблемы со старыми app",
        entries=(
            (r"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags", "DisableEngine", 1, 0),
            (r"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags", "DisablePCA", 1, 0),
        ),
        en_name="Disable AppCompat Engine",
        en_desc="DisableEngine=1, DisablePCA=1",
        en_hint="Less compatibility shims · rare old app issues",
    ),
    _b(
        "disable_ceip",
        "Отключить CEIP (SQM)",
        "SQMClient CEIPEnable=0",
        "privacy",
        "Customer Experience Improvement OFF · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Microsoft\SQMClient\Windows", "CEIPEnable", 0, 1),
        ),
        en_name="Disable CEIP (SQM)",
        en_desc="SQMClient CEIPEnable=0",
        en_hint="Customer Experience Improvement OFF · safe",
    ),
    _b(
        "disable_experimentation",
        "Отключить A/B эксперименты Windows",
        "AllowExperimentation=0",
        "privacy",
        "Windows не участвует в экспериментах · безопасно",
        risk="safe",
        entries=(
            (
                r"HKLM\SOFTWARE\Microsoft\PolicyManager\current\device\System",
                "AllowExperimentation",
                0,
                1,
            ),
        ),
        en_name="Disable Windows Experimentation",
        en_desc="AllowExperimentation=0",
        en_hint="No Windows A/B experiments · safe",
    ),
    _b(
        "disable_device_metadata_network",
        "Отключить загрузку метаданных устройств",
        "PreventDeviceMetadataFromNetwork=1",
        "privacy",
        "Устройства без online metadata · безопасно",
        risk="safe",
        entries=(
            (
                r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Device Metadata",
                "PreventDeviceMetadataFromNetwork",
                1,
                0,
            ),
        ),
        en_name="Disable Device Metadata from Network",
        en_desc="PreventDeviceMetadataFromNetwork=1",
        en_hint="No online device metadata · safe",
    ),
    _b(
        "disable_bluetooth_advertising",
        "Отключить Bluetooth Advertising",
        "AllowAdvertising=0 policy",
        "privacy",
        "Меньше BLE beacon · безопасно",
        risk="safe",
        entries=(
            (
                r"HKLM\SOFTWARE\Microsoft\PolicyManager\default\Bluetooth",
                "AllowAdvertising",
                0,
                1,
            ),
        ),
        en_name="Disable Bluetooth Advertising",
        en_desc="AllowAdvertising=0 policy",
        en_hint="Less BLE beaconing · safe",
    ),
    _b(
        "disable_handwriting_data_sharing",
        "Отключить сбор данных рукописного ввода",
        "RestrictImplicitTextCollection/InkCollection=1",
        "privacy",
        "Ink/typing не уходит в облако · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Software\Microsoft\InputPersonalization", "RestrictImplicitTextCollection", 1, 0),
            (r"HKCU\Software\Microsoft\InputPersonalization", "RestrictImplicitInkCollection", 1, 0),
        ),
        en_name="Disable Handwriting Data Sharing",
        en_desc="RestrictImplicitTextCollection/InkCollection=1",
        en_hint="Ink data stays local · safe",
    ),
    _b(
        "disable_linguistic_data_collection",
        "Отключить сбор лингвистических данных",
        "AllowLinguisticDataCollection=0",
        "privacy",
        "Меньше данных для IME/typing · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Software\Microsoft\Input\TIPC", "AllowLinguisticDataCollection", 0, 1),
        ),
        en_name="Disable Linguistic Data Collection",
        en_desc="AllowLinguisticDataCollection=0",
        en_hint="Less IME/typing cloud data · safe",
    ),
    _b(
        "disable_voice_app_activation",
        "Отключить голосовую активацию приложений",
        "VoiceActivation UserPreference=0",
        "privacy",
        "«Hey Cortana» / voice wake OFF · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (
                r"HKCU\Software\Microsoft\Speech_OneCore\Settings\VoiceActivation",
                "UserPreference",
                0,
                1,
            ),
        ),
        en_name="Disable Voice App Activation",
        en_desc="VoiceActivation UserPreference=0",
        en_hint="Hey Cortana / voice wake OFF · safe",
    ),
    _b(
        "disable_projection_to_pc",
        "Отключить Projection to PC",
        "AllowProjectionToPC=0",
        "privacy",
        "Нельзя проецировать экран на этот ПК · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Connect", "AllowProjectionToPC", 0, 1),
        ),
        en_name="Disable Projection to PC",
        en_desc="AllowProjectionToPC=0",
        en_hint="Cannot project screen to this PC · safe",
    ),
    _b(
        "disable_automatic_restart_signon",
        "Отключить авто-вход после перезагрузки",
        "DisableAutomaticRestartSignOn=1",
        "privacy",
        "После update reboot нужен пароль · безопаснее",
        risk="safe",
        entries=(
            (
                r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
                "DisableAutomaticRestartSignOn",
                1,
                0,
            ),
        ),
        en_name="Disable Automatic Restart Sign-On",
        en_desc="DisableAutomaticRestartSignOn=1",
        en_hint="Password required after update reboot · safer",
    ),
    _b(
        "disable_smart_glass",
        "Отключить SmartGlass / Xbox Companion",
        "UserAuthPolicy=Never",
        "privacy",
        "Xbox SmartGlass auth OFF · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\SmartGlass", "UserAuthPolicy", "Never", "Always", winreg.REG_SZ),
        ),
        en_name="Disable SmartGlass",
        en_desc="UserAuthPolicy=Never",
        en_hint="Xbox SmartGlass auth OFF · safe",
    ),
    _b(
        "disable_browser_language_leak",
        "Скрыть язык браузера (Accept-Language)",
        "TranslateEnabled=0 и HideBuiltInHelp=1 policies",
        "privacy",
        "Меньше fingerprint через язык · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Edge", "TranslateEnabled", 0, 1),
            (r"HKLM\SOFTWARE\Policies\Google\Chrome", "BrowserSignin", 0, 1),
        ),
        en_name="Reduce Browser Language Leak",
        en_desc="TranslateEnabled=0 and related browser policies",
        en_hint="Less language fingerprinting · safe",
    ),
    _b(
        "disable_edge_new_tab_feed",
        "Edge: отключить ленту New Tab",
        "NewTabPageContentEnabled=0, HideFirstRunExperience=1",
        "privacy",
        "Чистая новая вкладка Edge · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Edge", "NewTabPageContentEnabled", 0, 1),
            (r"HKLM\SOFTWARE\Policies\Microsoft\Edge", "HideFirstRunExperience", 1, 0),
        ),
        en_name="Edge: Disable New Tab Feed",
        en_desc="NewTabPageContentEnabled=0, HideFirstRunExperience=1",
        en_hint="Clean Edge new tab · safe",
    ),
    _b(
        "disable_news_and_interests",
        "Отключить News and Interests / Widgets",
        "AllowNewsAndInterests=0, ShellFeedsTaskbarViewMode=2",
        "privacy",
        "Без виджетов/новостей на панели · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds", "EnableFeeds", 0, 1),
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\Feeds", "ShellFeedsTaskbarViewMode", 2, 0),
        ),
        en_name="Disable News and Interests / Widgets",
        en_desc="EnableFeeds=0, ShellFeedsTaskbarViewMode=2",
        en_hint="No taskbar news/widgets · safe",
    ),
    _b(
        "disable_suggested_apps_toast",
        "Отключить toast «рекомендуемые приложения»",
        "SubscribedContent-310093, SystemPaneSuggestionsEnabled=0",
        "privacy",
        "Меньше pop-up рекомендаций Store · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_CDM, "SubscribedContent-310093Enabled", 0, 1),
            (_CDM, "SystemPaneSuggestionsEnabled", 0, 1),
        ),
        en_name="Disable Suggested Apps Toast",
        en_desc="SubscribedContent-310093, SystemPaneSuggestionsEnabled=0",
        en_hint="Fewer Store recommendation pop-ups · safe",
    ),
    _b(
        "disable_file_history",
        "Отключить File History",
        "DisableFileHistory=1 policy",
        "privacy",
        "История файлов OFF · используйте свой бэкап",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\FileHistory", "Disabled", 1, 0),
        ),
        en_name="Disable File History",
        en_desc="DisableFileHistory Disabled=1 policy",
        en_hint="File History OFF · use your own backup",
    ),
    _b(
        "disable_camera_on_off_notify",
        "Отключить уведомления камеры вкл/выкл",
        "NoPhysicalCameraLED=1, DisableCameraOnOffNotifications=1",
        "privacy",
        "Меньше toast при доступе к камере · безопасно",
        risk="safe",
        entries=(
            (
                r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam",
                "ShowGlobalPrompts",
                0,
                1,
            ),
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Camera", "DisableCameraOnOffNotifications", 1, 0),
        ),
        en_name="Disable Camera On/Off Notifications",
        en_desc="DisableCameraOnOffNotifications and related keys",
        en_hint="Fewer camera access toasts · safe",
    ),
    _b(
        "prevent_dev_home_outlook_bitlocker",
        "Заблокировать Dev Home / Outlook / BitLocker nudge",
        "AllowDevHome=0, DisableSetupOutOfBoxExperience=1",
        "privacy",
        "Меньше setup-nudge от Microsoft · безопасно",
        risk="safe",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\DevHome", "AllowDevHome", 0, 1),
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\OOBE", "DisableSetupOutOfBoxExperience", 1, 0),
        ),
        en_name="Block Dev Home / OOBE Nudges",
        en_desc="AllowDevHome=0, DisableSetupOutOfBoxExperience=1",
        en_hint="Fewer Microsoft setup nudges · safe",
    ),
    _b(
        "disable_focus_assist",
        "Отключить Focus Assist",
        "QuietHoursEnabled=0 и NOC_GLOBAL_SETTING_ALLOW_QUIET_HOURS=0",
        "privacy",
        "Focus Assist всегда OFF · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (
                r"HKCU\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings",
                "NOC_GLOBAL_SETTING_ALLOW_QUIET_HOURS",
                0,
                1,
            ),
            (
                r"HKCU\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\Cache\DefaultAccount\$windows.data.notifications.quietmoment\Current",
                "Data",
                b"\x02\x00\x00\x00\x00\x00\x00\x00",
                None,
                winreg.REG_BINARY,
            ),
        ),
        en_name="Disable Focus Assist",
        en_desc="QuietHoursEnabled=0 and related notification keys",
        en_hint="Focus Assist always OFF · safe",
    ),
    _b(
        "disable_scooobe_ads",
        "Отключить Scoobe / setup рекламу",
        "SubscribedContent-338393/353694 Enabled=0",
        "privacy",
        "Меньше рекламы после установки Windows · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_CDM, "SubscribedContent-338393Enabled", 0, 1),
            (_CDM, "SubscribedContent-353694Enabled", 0, 1),
            (_CDM, "PreInstalledAppsEnabled", 0, 1),
        ),
        en_name="Disable Scoobe / Setup Ads",
        en_desc="SubscribedContent-338393/353694 Enabled=0",
        en_hint="Less post-install Windows ads · safe",
    ),
    _b(
        "disable_nfc",
        "Отключить NFC",
        "NfcSvc Start=4 + DisableRemoteNfc=1",
        "privacy",
        "NFC OFF · NfcSvc Start=4 · перезагрузка",
        reboot=True,
        entries=(
            (r"HKLM\SYSTEM\CurrentControlSet\Services\NfcSvc", "Start", 4, 3),
            (r"HKLM\SOFTWARE\Policies\Microsoft\Nfc", "DisableRemoteNfc", 1, 0),
        ),
        en_name="Disable NFC",
        en_desc="NfcSvc Start=4 and DisableRemoteNfc=1",
        en_hint="NFC OFF · NfcSvc Start=4 · reboot",
    ),
    # ── Expert ────────────────────────────────────────────────────────────
    _b(
        "disable_remote_desktop",
        "Отключить Remote Desktop",
        "fDenyTSConnections=1",
        "expert",
        "RDP вход OFF · безопаснее от сетевых атак",
        risk="high",
        entries=(
            (r"HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server", "fDenyTSConnections", 1, 0),
        ),
        en_name="Disable Remote Desktop",
        en_desc="fDenyTSConnections=1",
        en_hint="RDP inbound OFF · safer from network attacks",
    ),
    _b(
        "disable_remote_assistance",
        "Отключить Remote Assistance",
        "fAllowToGetHelp=0",
        "expert",
        "Удалённая помощь OFF · безопаснее",
        risk="high",
        entries=(
            (
                r"HKLM\SYSTEM\CurrentControlSet\Control\Remote Assistance",
                "fAllowToGetHelp",
                0,
                1,
            ),
        ),
        en_name="Disable Remote Assistance",
        en_desc="fAllowToGetHelp=0",
        en_hint="Remote Assistance OFF · safer",
    ),
    _b(
        "disable_smartscreen_only",
        "Отключить только SmartScreen",
        "SmartScreenEnabled=Off без полного Defender",
        "expert",
        "Эксперт · меньше блокировок файлов · без антивируса не рекомендуется",
        risk="high",
        entries=(
            (_EXPL, "SmartScreenEnabled", "Off", "Warn", winreg.REG_SZ),
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\System", "EnableSmartScreen", 0, 1),
            (r"HKLM\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter", "EnabledV9", 0, 1),
        ),
        en_name="Disable SmartScreen Only",
        en_desc="SmartScreenEnabled=Off without full Defender disable",
        en_hint="Expert · fewer file blocks · risky without AV",
    ),
    _b(
        "disable_network_guest_sharing",
        "Отключить гостевой доступ SMB",
        "AllowInsecureGuestAuth=0",
        "expert",
        "Без anonymous/guest SMB · безопаснее в LAN",
        entries=(
            (
                r"HKLM\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters",
                "AllowInsecureGuestAuth",
                0,
                1,
            ),
        ),
        en_name="Disable Network Guest Sharing",
        en_desc="AllowInsecureGuestAuth=0",
        en_hint="No anonymous/guest SMB · safer on LAN",
    ),
    _b(
        "disable_tpm_enforce",
        "Обход TPM/Secure Boot (LabConfig)",
        "BypassTPMCheck, BypassSecureBootCheck — Win11 установка",
        "expert",
        "Win11 niche · только для legacy ПК · высокий риск",
        risk="high",
        entries=(
            (r"HKLM\SYSTEM\Setup\LabConfig", "BypassTPMCheck", 1, 0),
            (r"HKLM\SYSTEM\Setup\LabConfig", "BypassSecureBootCheck", 1, 0),
            (r"HKLM\SYSTEM\Setup\LabConfig", "BypassRAMCheck", 1, 0),
        ),
        en_name="Bypass TPM/Secure Boot (LabConfig)",
        en_desc="BypassTPMCheck, BypassSecureBootCheck for Win11 install",
        en_hint="Win11 niche · legacy PCs only · high risk",
    ),
    _b(
        "remove_lock_screen",
        "Убрать экран блокировки",
        "NoLockScreen=1 policy",
        "visual",
        "Сразу на рабочий стол · менее безопасно в офисе",
        entries=(
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization", "NoLockScreen", 1, 0),
        ),
        en_name="Remove Lock Screen",
        en_desc="NoLockScreen=1 policy",
        en_hint="Straight to desktop · less secure in offices",
    ),
    _b(
        "disable_biometrics",
        "Отключить Windows Hello / биометрию",
        "Службы WbioSrvc и связанные — handler в backlog.py",
        "expert",
        "Windows Hello OFF · откат через handler",
        entries=(),
        en_name="Disable Windows Hello / Biometrics",
        en_desc="WbioSrvc and related services disabled via handler",
        en_hint="Windows Hello OFF · revert via handler",
    ),
    _b(
        "pause_updates_extreme",
        "Пауза обновлений до 2077",
        "FlightSettingsMaxPauseDays=36500, PauseFeatureUpdatesStartTime",
        "expert",
        "Эксперт · система без патчей · крайняя мера",
        risk="high",
        entries=PAUSE_UPDATES_EXTREME_ENTRIES,
        en_name="Pause Updates Until 2077",
        en_desc="FlightSettingsMaxPauseDays=36500 and pause keys",
        en_hint="Expert · no security patches · extreme measure",
    ),
    # ── Visual / UI ───────────────────────────────────────────────────────
    _b(
        "disable_snap_assist",
        "Отключить Snap Assist",
        "WindowArrangementActive=0, SnapAssist keys",
        "visual",
        "Без подсказок при snap окон · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Control Panel\Desktop", "WindowArrangementActive", 0, 1),
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "SnapAssist", 0, 1),
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DITest", 0, 1),
        ),
        en_name="Disable Snap Assist",
        en_desc="WindowArrangementActive=0, SnapAssist keys",
        en_hint="No snap layout hints · safe",
    ),
    _b(
        "disable_recent_programs_start",
        "Скрыть недавние программы в Пуске",
        "NoStartMenuMFUprogramsList=1",
        "visual",
        "Приватнее меню Пуск · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_POL, "NoStartMenuMFUprogramsList", 1, 0),
        ),
        en_name="Hide Recent Programs in Start",
        en_desc="NoStartMenuMFUprogramsList=1",
        en_hint="More private Start menu · safe",
    ),
    _b(
        "disable_people_band",
        "Отключить People Band на панели задач",
        "PeopleBand=0",
        "visual",
        "Win10 People bar OFF · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_ADV, "PeopleBand", 0, 1),
        ),
        en_name="Disable People Band",
        en_desc="PeopleBand=0",
        en_hint="Win10 People bar OFF · safe",
    ),
    _b(
        "disable_sync_provider_notifications",
        "Отключить уведомления Sync Provider",
        "ShowSyncProviderNotifications=0",
        "visual",
        "Меньше OneDrive/sync toast · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_ADV, "ShowSyncProviderNotifications", 0, 1),
        ),
        en_name="Disable Sync Provider Notifications",
        en_desc="ShowSyncProviderNotifications=0",
        en_hint="Fewer OneDrive/sync toasts · safe",
    ),
    _b(
        "disable_window_shaking",
        "Отключить Aero Shake",
        "DisallowShaking=1",
        "visual",
        "Shake title bar не сворачивает окна · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_ADV, "DisallowShaking", 1, 0),
        ),
        en_name="Disable Aero Shake",
        en_desc="DisallowShaking=1",
        en_hint="Title bar shake won't minimize windows · safe",
    ),
    _b(
        "align_taskbar_left",
        "Панель задач слева (Win11)",
        "TaskbarAl=0",
        "visual",
        "Win11 only · классическое выравнивание · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "TaskbarAl", 0, 1),
        ),
        en_name="Align Taskbar Left (Win11)",
        en_desc="TaskbarAl=0",
        en_hint="Win11 only · classic alignment · safe",
    ),
    _b(
        "set_24_hour_clock",
        "24-часовой формат времени",
        "sTimeFormat=HH:mm:ss",
        "visual",
        "24h clock в трее · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Control Panel\International", "sTimeFormat", "HH:mm:ss", "h:mm:ss tt", winreg.REG_SZ),
            (r"HKCU\Control Panel\International", "sShortTime", "HH:mm", "h:mm tt", winreg.REG_SZ),
        ),
        en_name="24-Hour Clock Format",
        en_desc="sTimeFormat=HH:mm:ss",
        en_hint="24h clock in tray · safe",
    ),
    _b(
        "show_detailed_bsod",
        "Подробный BSOD (DisplayParameters)",
        "DisplayParameters=1 в CrashControl",
        "system",
        "Полный код ошибки на синем экране · для диагностики",
        risk="safe",
        entries=(
            (r"HKLM\SYSTEM\CurrentControlSet\Control\CrashControl", "DisplayParameters", 1, 0),
        ),
        en_name="Detailed BSOD (DisplayParameters)",
        en_desc="DisplayParameters=1 in CrashControl",
        en_hint="Full error code on blue screen · for diagnostics",
    ),
    _b(
        "disable_rdp_unsigned_warn",
        "Отключить предупреждение RDP unsigned",
        "AuthenticationLevelOverride=0",
        "expert",
        "Эксперт · менее безопасные RDP-сессии",
        risk="high",
        entries=(
            (
                r"HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services",
                "AuthenticationLevelOverride",
                0,
                1,
            ),
        ),
        en_name="Disable RDP Unsigned Warning",
        en_desc="AuthenticationLevelOverride=0",
        en_hint="Expert · less secure RDP sessions",
    ),
    _b(
        "set_time_utc",
        "Hardware clock в UTC",
        "RealTimeIsUniversal=1",
        "system",
        "Dual-boot Linux/macOS · перезагрузка",
        reboot=True,
        entries=(
            (r"HKLM\SYSTEM\CurrentControlSet\Control\TimeZoneInformation", "RealTimeIsUniversal", 1, 0),
        ),
        en_name="Hardware Clock in UTC",
        en_desc="RealTimeIsUniversal=1",
        en_hint="For dual-boot Linux/macOS · reboot",
    ),
    _b(
        "enable_aero_shake",
        "Включить Aero Shake",
        "DisallowShaking=0 — shake сворачивает окна",
        "visual",
        "Обратный твик disable_window_shaking · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_ADV, "DisallowShaking", 0, 1),
        ),
        en_name="Enable Aero Shake",
        en_desc="DisallowShaking=0 — shake minimizes windows",
        en_hint="Reverse of disable_window_shaking · safe",
    ),
    _b(
        "hide_gallery_home_explorer",
        "Скрыть Gallery в проводнике",
        "IsPinnedToNameSpaceTree=0 для Gallery CLSID",
        "visual",
        "Win11 Gallery tab hidden · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (
                r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{e88865ea-0e1c-4e20-9aa6-aecd971cab5a}",
                "HideIfEnabled",
                1,
                0,
            ),
        ),
        en_name="Hide Gallery in Explorer",
        en_desc="IsPinnedToNameSpaceTree=0 for Gallery CLSID",
        en_hint="Win11 Gallery tab hidden · safe",
    ),
    _b(
        "hide_network_pane_explorer",
        "Скрыть сеть в проводнике",
        "HideNetworkLocations=1",
        "visual",
        "Network в Explorer hidden · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_ADV, "HideNetworkLocations", 1, 0),
        ),
        en_name="Hide Network in Explorer",
        en_desc="HideNetworkLocations=1",
        en_hint="Network pane hidden in Explorer · safe",
    ),
    _b(
        "hide_removable_drives_explorer",
        "Скрыть съёмные диски в проводнике",
        "HideDrivesWithNoMedia=1",
        "visual",
        "Пустые card reader скрыты · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_ADV, "HideDrivesWithNoMedia", 1, 0),
        ),
        en_name="Hide Removable Drives in Explorer",
        en_desc="HideDrivesWithNoMedia=1",
        en_hint="Empty card readers hidden · safe",
    ),
    _b(
        "enable_explorer_checkboxes",
        "Чекбоксы выбора в проводнике",
        "AutoCheckSelect=1",
        "visual",
        "Checkbox selection в Explorer · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_ADV, "AutoCheckSelect", 1, 0),
        ),
        en_name="Enable Explorer Checkboxes",
        en_desc="AutoCheckSelect=1",
        en_hint="Checkbox selection in Explorer · safe",
    ),
    _b(
        "pin_recycle_bin_explorer",
        "Закрепить корзину в проводнике",
        "Desktop NameSpace {645FF040-5081-101B-9F08-00AA002F954E}",
        "visual",
        "Recycle Bin в sidebar Explorer · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (
                r"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{645FF040-5081-101B-9F08-00AA002F954E}",
                "",
                "",
                None,
                winreg.REG_SZ,
            ),
        ),
        en_name="Pin Recycle Bin in Explorer",
        en_desc="Desktop NameSpace Recycle Bin CLSID",
        en_hint="Recycle Bin in Explorer sidebar · safe",
    ),
    _b(
        "hide_settings_homepage",
        "Скрыть главную Settings",
        "SettingsPageVisibility=hide:home",
        "visual",
        "Settings opens без home page · безопасно",
        risk="safe",
        entries=(
            (_EXPL_POL, "SettingsPageVisibility", "hide:home", "", winreg.REG_SZ),
        ),
        en_name="Hide Settings Homepage",
        en_desc="SettingsPageVisibility=hide:home",
        en_hint="Settings opens without home page · safe",
    ),
    _b(
        "show_full_app_name_shortcuts",
        "Полные имена ярлыков",
        "LinkResolveIgnoreLinkInfo=1",
        "visual",
        "Ярлыки показывают полное имя exe · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (_EXPL_ADV, "LinkResolveIgnoreLinkInfo", 1, 0),
        ),
        en_name="Show Full App Names on Shortcuts",
        en_desc="LinkResolveIgnoreLinkInfo=1",
        en_hint="Shortcuts show full exe name · safe",
    ),
    _b(
        "disable_cast_to_device",
        "Отключить Cast to Device",
        "Blocked shell extension {7AD84985-97B4-4BD7-A8BE-6DF805E94494}",
        "visual",
        "ПКМ Cast to Device hidden · безопасно",
        risk="safe",
        entries=(
            (
                r"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked",
                "{7AD84985-97B4-4BD7-A8BE-6DF805E94494}",
                "",
                None,
                winreg.REG_SZ,
            ),
        ),
        en_name="Disable Cast to Device",
        en_desc="Block Cast to Device shell extension",
        en_hint="Cast to Device removed from context menu · safe",
    ),
    _b(
        "enable_legacy_volume_sliders",
        "Классические ползунки громкости",
        "EnableMtcUvc=0 — Win10 legacy mixer",
        "visual",
        "Win10 classic volume overlay · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Software\Microsoft\Windows NT\CurrentVersion\MTCUVC", "EnableMtcUvc", 0, 1),
        ),
        en_name="Legacy Volume Sliders",
        en_desc="EnableMtcUvc=0 — Win10 classic mixer",
        en_hint="Win10 classic volume overlay · safe",
    ),
    _b(
        "mouse_hover_time_zero",
        "Мгновенный hover (MouseHoverTime=0)",
        "MouseHoverTime=0 в Control Panel\\Mouse",
        "visual",
        "Tooltips появляются сразу · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Control Panel\Mouse", "MouseHoverTime", "0", "400", winreg.REG_SZ),
        ),
        en_name="Instant Mouse Hover (MouseHoverTime=0)",
        en_desc="MouseHoverTime=0 in Control Panel\\Mouse",
        en_hint="Tooltips appear instantly · safe",
    ),
    _b(
        "disable_toggle_keys",
        "Отключить Toggle Keys",
        "ToggleKeys Flags=506",
        "visual",
        "Без звука Caps/Num/Scroll · безопасно",
        risk="safe",
        admin=False,
        entries=(
            (r"HKCU\Control Panel\Accessibility\ToggleKeys", "Flags", "506", "58", winreg.REG_SZ),
        ),
        en_name="Disable Toggle Keys",
        en_desc="ToggleKeys Flags=506",
        en_hint="No Caps/Num/Scroll beep · safe",
    ),
    _b(
        "disable_update_notifications",
        "Отключить уведомления Windows Update",
        "UxOption=1, SetDisableUXWUAccess=1",
        "visual",
        "Меньше WU toast · обновления всё равно могут ставиться",
        risk="safe",
        entries=(
            (_WU, "UxOption", 1, 0),
            (r"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate", "SetDisableUXWUAccess", 1, 0),
        ),
        en_name="Disable Windows Update Notifications",
        en_desc="UxOption=1, SetDisableUXWUAccess=1",
        en_hint="Fewer WU toasts · updates may still install",
    ),
    _b(
        "configure_wu_deferral",
        "Отложить Feature/Quality Updates",
        "DeferFeatureUpdatesPeriodInDays=365, DeferQualityUpdatesPeriodInDays=30",
        "system",
        "Updates откладываются · патчи приходят позже",
        entries=(
            (_WU_POL, "DeferFeatureUpdates", 1, 0),
            (_WU_POL, "DeferFeatureUpdatesPeriodInDays", 365, 0),
            (_WU_POL, "DeferQualityUpdates", 1, 0),
            (_WU_POL, "DeferQualityUpdatesPeriodInDays", 30, 0),
        ),
        en_name="Defer Feature/Quality Updates",
        en_desc="DeferFeatureUpdatesPeriodInDays=365, DeferQualityUpdatesPeriodInDays=30",
        en_hint="Updates delayed · patches arrive later",
    ),
    _b(
        "context_copy_move_to",
        "ПКМ: Copy/Move to folder",
        "CopyTo/MoveTo shell menu handlers",
        "expert",
        "Доп. пункты контекстного меню · безопасно",
        risk="safe",
        entries=(
            (
                r"HKLM\SOFTWARE\Classes\AllFilesystemObjects\shellex\ContextMenuHandlers\Copy To",
                "",
                "{C2FBB630-2971-11D1-A18C-00C04FD75D67}",
                None,
                winreg.REG_SZ,
            ),
            (
                r"HKLM\SOFTWARE\Classes\AllFilesystemObjects\shellex\ContextMenuHandlers\Move To",
                "",
                "{C2FBB630-2971-11D1-A18C-00C04FD75D67}",
                None,
                winreg.REG_SZ,
            ),
        ),
        en_name="Context Menu: Copy/Move To",
        en_desc="CopyTo/MoveTo shell menu handlers",
        en_hint="Extra context menu items · safe",
    ),
    _b(
        "restore_legacy_photo_viewer",
        "Вернуть Windows Photo Viewer",
        "Регистрация PhotoViewer.dll — handler в backlog.py",
        "visual",
        "Классический просмотр фото · handler с полным набором ключей",
        risk="safe",
        entries=(),
        en_name="Restore Legacy Photo Viewer",
        en_desc="Register PhotoViewer.dll — full handler in backlog.py",
        en_hint="Classic photo viewer · full reg handler in backlog.py",
    ),
    # ── Services (handlers in backlog.py) ─────────────────────────────────
    _b(
        "disable_ndu_service",
        "Отключить NDU (Ndu)",
        "Network Data Usage Monitor — Start=4",
        "network",
        "Меньше DPC latency от NDU · популярный gaming tweak",
        reboot=True,
        entries=(),
        en_name="Disable NDU Service",
        en_desc="Network Data Usage Monitor service Start=4",
        en_hint="Less DPC latency from NDU · popular gaming tweak",
    ),
    _b(
        "disable_pca_service",
        "Отключить PcaSvc",
        "Program Compatibility Assistant — Start=4",
        "performance",
        "Меньше фоновых compat checks · перезагрузка",
        reboot=True,
        entries=(),
        en_name="Disable PcaSvc",
        en_desc="Program Compatibility Assistant Start=4",
        en_hint="Fewer background compat checks · reboot",
    ),
    _b(
        "disable_pla_service",
        "Отключить Performance Logs (pla)",
        "Performance Logs and Alerts — Start=4",
        "performance",
        "Меньше perf counter logging · безопасно на desktop",
        reboot=True,
        entries=(),
        en_name="Disable Performance Logs (pla)",
        en_desc="Performance Logs and Alerts Start=4",
        en_hint="Less perf counter logging · safe on desktop",
    ),
    _b(
        "disable_wap_push",
        "Отключить WAP Push (dmwappushservice)",
        "dmwappushservice — Start=4",
        "privacy",
        "Меньше push telemetry · перезагрузка",
        reboot=True,
        entries=(),
        en_name="Disable WAP Push Service",
        en_desc="dmwappushservice Start=4",
        en_hint="Less push telemetry · reboot",
    ),
    _b(
        "disable_geolocation_service",
        "Отключить Geolocation Service",
        "lfsvc — Start=4",
        "privacy",
        "Геолокация OFF · перезагрузка",
        reboot=True,
        entries=(),
        en_name="Disable Geolocation Service",
        en_desc="lfsvc Start=4",
        en_hint="Geolocation OFF · reboot",
    ),
    _b(
        "disable_fax_service",
        "Отключить Fax Service",
        "Fax — Start=4",
        "system",
        "Fax OFF · безопасно если факс не нужен",
        risk="safe",
        reboot=True,
        entries=(),
        en_name="Disable Fax Service",
        en_desc="Fax service Start=4",
        en_hint="Fax OFF · safe if unused",
    ),
    _b(
        "disable_branchcache",
        "Отключить BranchCache",
        "PeerDistSvc — Start=4",
        "network",
        "P2P cache OFF · безопасно на home PC",
        risk="safe",
        reboot=True,
        entries=(),
        en_name="Disable BranchCache",
        en_desc="PeerDistSvc Start=4",
        en_hint="P2P cache OFF · safe on home PC",
    ),
    _b(
        "disable_wallet_service",
        "Отключить Wallet Service",
        "WalletService — Start=4",
        "privacy",
        "Microsoft Pay/Wallet OFF · безопасно",
        risk="safe",
        reboot=True,
        entries=(),
        en_name="Disable Wallet Service",
        en_desc="WalletService Start=4",
        en_hint="Microsoft Pay/Wallet OFF · safe",
    ),
    _b(
        "disable_mobile_hotspot",
        "Отключить Mobile Hotspot",
        "icssvc — Start=4",
        "network",
        "Раздача Wi-Fi OFF · если hotspot не нужен",
        reboot=True,
        entries=(),
        en_name="Disable Mobile Hotspot",
        en_desc="icssvc Start=4",
        en_hint="Wi-Fi hotspot OFF · if unused",
    ),
    _b(
        "disable_print_spooler",
        "Отключить Print Spooler",
        "Spooler — Start=4 (gaming)",
        "gaming",
        "Gaming tweak · печать не будет работать",
        risk="high",
        reboot=True,
        entries=(),
        en_name="Disable Print Spooler",
        en_desc="Spooler Start=4 — gaming tweak",
        en_hint="Gaming tweak · printing won't work",
    ),
    _b(
        "disable_tablet_input_service",
        "Отключить Tablet Input Service",
        "TabletInputService — Start=4",
        "performance",
        "Touch/pen input OFF · только без сенсорного экрана",
        reboot=True,
        entries=(),
        en_name="Disable Tablet Input Service",
        en_desc="TabletInputService Start=4",
        en_hint="Touch/pen OFF · only without touchscreen",
    ),
    _b(
        "disable_dcp_service",
        "Отключить Data Collection Publisher",
        "DcpSvc — Start=4",
        "privacy",
        "Меньше data collection · перезагрузка",
        reboot=True,
        entries=(),
        en_name="Disable Data Collection Publisher",
        en_desc="DcpSvc Start=4",
        en_hint="Less data collection · reboot",
    ),
    _b(
        "disable_remote_registry",
        "Отключить Remote Registry",
        "RemoteRegistry — Start=4",
        "expert",
        "Удалённый доступ к реестру OFF · безопаснее",
        risk="high",
        reboot=True,
        entries=(),
        en_name="Disable Remote Registry",
        en_desc="RemoteRegistry Start=4",
        en_hint="Remote registry access OFF · safer",
    ),
    _b(
        "disable_alljoyn_router",
        "Отключить AllJoyn Router",
        "AJRouter — Start=4",
        "network",
        "IoT AllJoyn OFF · безопасно на desktop",
        risk="safe",
        reboot=True,
        entries=(),
        en_name="Disable AllJoyn Router",
        en_desc="AJRouter Start=4",
        en_hint="IoT AllJoyn OFF · safe on desktop",
    ),
    _b(
        "disable_media_player_sharing",
        "Отключить Windows Media Player Sharing",
        "WMPNetworkSvc — Start=4",
        "privacy",
        "DLNA sharing OFF · безопасно",
        risk="safe",
        reboot=True,
        entries=(),
        en_name="Disable Media Player Sharing",
        en_desc="WMPNetworkSvc Start=4",
        en_hint="DLNA sharing OFF · safe",
    ),
    _b(
        "disable_smart_card",
        "Отключить Smart Card",
        "SCardSvr — Start=4",
        "system",
        "Smart card reader OFF · если не используется",
        risk="safe",
        reboot=True,
        entries=(),
        en_name="Disable Smart Card Service",
        en_desc="SCardSvr Start=4",
        en_hint="Smart card OFF · if unused",
    ),
    _b(
        "disable_pim_index",
        "Отключить Contact Data (PimIndex)",
        "PimIndexMaintenanceSvc — Start=4",
        "privacy",
        "Contact indexing OFF · перезагрузка",
        reboot=True,
        entries=(),
        en_name="Disable Contact Data (PimIndex)",
        en_desc="PimIndexMaintenanceSvc Start=4",
        en_hint="Contact indexing OFF · reboot",
    ),
    _b(
        "disable_retail_demo",
        "Отключить Retail Demo Service",
        "RetailDemo — Start=4",
        "system",
        "Retail demo mode OFF · безопасно",
        risk="safe",
        reboot=True,
        entries=(),
        en_name="Disable Retail Demo Service",
        en_desc="RetailDemo Start=4",
        en_hint="Retail demo mode OFF · safe",
    ),
    _b(
        "disable_parental_controls",
        "Отключить Parental Controls",
        "WpcMonSvc — Start=4",
        "privacy",
        "Family Safety monitor OFF · если не нужен",
        risk="safe",
        reboot=True,
        entries=(),
        en_name="Disable Parental Controls",
        en_desc="WpcMonSvc Start=4",
        en_hint="Family Safety monitor OFF · if unused",
    ),
    # ── Action / script handlers (entries in backlog.py) ───────────────────
    _b(
        "optimize_netsh_gaming",
        "Netsh: игровой TCP-профиль",
        "Autotuning off, timestamps off, CTCP, ECN — профиль из Sparkle/OptimizerNXT",
        "network",
        "Перезапустите игру после применения · откат через «Откатить»",
        risk="medium",
        reboot=False,
        entries=(),
        en_name="Netsh: Gaming TCP Profile",
        en_desc="Autotuning off, timestamps off, CTCP, ECN",
        en_hint="Restart game after apply · revert via Restore",
    ),
    _b(
        "disable_boot_splash",
        "Отключить анимацию загрузки",
        "bcdedit bootuxdisabled on — быстрее вход в систему",
        "performance",
        "Перезагрузка обязательна · bcdedit",
        reboot=True,
        entries=(),
        en_name="Disable Boot Splash Animation",
        en_desc="bcdedit bootuxdisabled on",
        en_hint="Reboot required · bcdedit",
    ),
    _b(
        "disable_nic_lso",
        "Отключить LSO на NIC",
        "Large Send Offload OFF на активных адаптерах — меньше latency",
        "network",
        "Требует PowerShell · перезапуск сети/игры",
        risk="medium",
        reboot=False,
        entries=(),
        en_name="Disable NIC Large Send Offload",
        en_desc="LSO off on active adapters — lower latency",
        en_hint="Requires PowerShell · restart network/game",
    ),
    _b(
        "disable_usb_selective_suspend",
        "Отключить USB Selective Suspend",
        "USB не засыпает — меньше лагов мыши/контроллера",
        "performance",
        "USB не засыпает — реестр + powercfg (GUID). На кастомных планах (PowerX) — только реестр",
        risk="safe",
        reboot=False,
        entries=(),
        en_name="Disable USB Selective Suspend",
        en_desc="USB stays awake — fewer mouse/controller lag spikes",
        en_hint="powercfg · useful for gaming peripherals",
    ),
    _b(
        "disable_cpu_core_parking",
        "Отключить Core Parking",
        "CPMINCORES=100% — все ядра активны под нагрузкой",
        "performance",
        "Больше энергопотребление · реестр + powercfg; на PowerX/кастомных планах — реестр",
        risk="medium",
        reboot=False,
        entries=(),
        en_name="Disable CPU Core Parking",
        en_desc="CPMINCORES 100% — all cores available under load",
        en_hint="Higher power draw · desktop/gaming",
    ),
    _b(
        "empty_standby_list",
        "Очистить Standby RAM",
        "Разовая очистка standby-списка перед игрой",
        "performance",
        "Разовое действие · не сохраняется после перезагрузки",
        risk="safe",
        reboot=False,
        admin=True,
        entries=(),
        en_name="Empty Standby List",
        en_desc="One-shot standby list cleanup before gaming",
        en_hint="One-shot · not persistent after reboot",
    ),
    _b(
        "debloat_uwp_apps",
        "Удалить bloat UWP",
        "Clipchamp, Solitaire, Teams, Xbox overlay и др. — разовое удаление",
        "system",
        "Разовое · Store-приложения можно вернуть только через Store",
        risk="medium",
        reboot=False,
        entries=(),
        en_name="Remove Bloat UWP Apps",
        en_desc="One-shot removal of Clipchamp, Solitaire, Teams, Xbox overlay, etc.",
        en_hint="One-shot · reinstall apps via Microsoft Store",
    ),
    _b(
        "kill_gaming_overlays",
        "Завершить overlay-процессы",
        "GameBarPresenceWriter, Xbox overlay — разовое",
        "gaming",
        "Разовое · overlay могут запуститься снова",
        risk="safe",
        reboot=False,
        admin=False,
        entries=(),
        en_name="Kill Gaming Overlays",
        en_desc="One-shot kill GameBarPresenceWriter and Xbox overlay",
        en_hint="One-shot · overlays may restart",
    ),
    _b(
        "flush_standby_memory",
        "Сбросить standby-память",
        "PowerShell-очистка standby RAM",
        "performance",
        "Разовое · перед требовательной игрой",
        risk="safe",
        reboot=False,
        entries=(),
        en_name="Flush Standby Memory",
        en_desc="One-shot PowerShell standby RAM cleanup",
        en_hint="One-shot · before demanding games",
    ),
    _b(
        "create_god_mode_folder",
        "Создать папку God Mode",
        "Ярлык GodMode на рабочем столе",
        "system",
        "Разовое · папку можно удалить вручную",
        risk="safe",
        reboot=False,
        admin=False,
        entries=(),
        en_name="Create God Mode Folder",
        en_desc="Desktop shortcut to Windows God Mode control panel",
        en_hint="One-shot · delete folder manually if unwanted",
    ),
    _b(
        "disable_telemetry_scheduled_tasks",
        "Отключить CEIP scheduled tasks",
        "Пакетное отключение задач Customer Experience Improvement",
        "privacy",
        "Разовое · schtasks · часть задач может вернуться после обновлений",
        risk="medium",
        reboot=False,
        entries=(),
        en_name="Disable CEIP Scheduled Tasks",
        en_desc="Batch-disable Customer Experience Improvement tasks",
        en_hint="One-shot schtasks · some tasks may return after updates",
    ),
    _b(
        "block_microsoft_telemetry_domains",
        "Блок telemetry-доменов (hosts)",
        "127.0.0.1 для vortex-win.data.microsoft.com и др. · backup hosts",
        "privacy",
        "Эксперт · правка hosts · откат из .hosts.crimsontune.bak",
        risk="high",
        reboot=False,
        entries=(),
        en_name="Block Microsoft Telemetry Domains (hosts)",
        en_desc="127.0.0.1 entries for Microsoft telemetry hosts",
        en_hint="Expert · hosts file · revert from backup",
    ),
    _b(
        "enable_compact_os",
        "Compact OS",
        "compact /CompactOS:always — сжатие системных файлов NTFS",
        "performance",
        "Разовое · экономия места · откат compact /CompactOS:never",
        risk="medium",
        reboot=True,
        entries=(),
        en_name="Enable Compact OS",
        en_desc="compact /CompactOS:always — NTFS compression for Windows files",
        en_hint="One-shot · saves disk space · revert with /CompactOS:never",
    ),
]
